# Generated by Django 3.1.4 on 2020-12-07 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllergenInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegan', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('lactose_free', models.BooleanField(default=False)),
                ('peanut_free', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allergen_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='selections.allergeninfo')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='selections.category')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='selections.category')),
                ('menu', models.ManyToManyField(null=True, to='selections.MenuItem')),
            ],
        ),
    ]
