# Generated by Django 3.1.4 on 2020-12-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selections', '0002_auto_20201207_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergeninfo',
            name='name',
        ),
    ]
